from fastapi import APIRouter
from pydantic import BaseModel
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
import logging

logger = logging.getLogger(__name__)
router = APIRouter()

_llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0, max_tokens=20)

_SYSTEM = (
    "Output only a 2-5 word project name from this spec. "
    "No quotes. No punctuation. No explanation. Just the name."
)

MAX_MD_CHARS = 3000


class NameRequest(BaseModel):
    project_md: str


class NameResponse(BaseModel):
    name: str


def _fallback_name(project_md: str) -> str:
    import re
    match = re.search(r"^#\s+(.+)$", project_md, re.MULTILINE)
    if match:
        candidate = match.group(1).strip()
        if candidate.lower() not in ("vision", "overview", "project", ""):
            return candidate
    return "Untitled Project"


@router.post("/api/name", response_model=NameResponse)
async def generate_name(req: NameRequest) -> NameResponse:
    """Return a 2-5 word project name generated by Groq from the project spec.

    Falls back to H1 heading extraction, then 'Untitled Project' if Groq fails.
    Never raises — callers should always get a usable name.
    """
    md = req.project_md[:MAX_MD_CHARS]
    try:
        response = await _llm.ainvoke([
            SystemMessage(content=_SYSTEM),
            HumanMessage(content=md),
        ])
        name = str(response.content).strip().strip('"').strip("'")
        if name:
            return NameResponse(name=name)
    except Exception as e:
        logger.warning("Groq name generation failed: %s", e)
    return NameResponse(name=_fallback_name(req.project_md))
